# springboot port
server:
  address: 0.0.0.0
  port:
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
        # 开发环境-服务器外网地址
        domain:

# spring 配置
spring:
  application:
    name: starsapi-backend
  # DataSource 配置
  datasource:
    driver-class-name:
    # 线上环境-本地地址-MySQL地址
    url:
    username:
    password:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session 配置
  session:
    timeout: 1800
    store-type: redis
  # redis 配置
  redis:
    port: 6379
    # 线上环境-本地地址-Redis地址
    host:
    database:
    password:
  # rabbitmq 配置
  rabbitmq:
    port: 5672
    # 线上环境-本地地址-RabbitMQ地址
    host:
    virtual-host: /
    username:
    password:

# mybatis 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0

# dubbo整合nacos 配置
dubbo:
  application:
    name:
    qos:
      # 是否启动QoS
      enable: true
      # 启动QoS绑定的端口
      port: 33010
      # 是否允许远程访问
      foregin:
        ip: true
  protocol:
    name:
    port:
  registry:
    id:
    # 线上环境-服务器内网地址-Nacos地址
    address:

# 阿里云 OSS 配置
aliyun:
  oss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    urlPrefix:
    accessKeyId:
    accessKeySecret:
    bucketName:
    fileHost: files
